# Generated by Django 3.0 on 2020-01-05 07:07

from django.db import migrations, models
import pwmanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('auth_key', models.CharField(max_length=255, unique=True)),
            ],
            managers=[
                ('objects', pwmanager.models.VaultUserManager),
            ],
        ),
    ]
