# Generated by Django 3.0.1 on 2020-06-05 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.UUID('d9e59a08-13c1-4b4d-b7b0-67f68f36440f'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('auth_key', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d4cf4396-6a5f-434b-bf96-0cb5c4d83506'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('vault_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
