# Generated by Django 3.0 on 2020-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vaultuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='vaultuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
    ]
