# Generated by Django 3.0.7 on 2020-12-24 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='id',
            field=models.UUIDField(default=uuid.UUID('214fb874-df20-4027-9da0-0618491fd244'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vaultuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('525a0f2e-f894-4eec-b96d-8091c6d358c3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
